[package]
name = "ayaya"
version = "0.1.0"
authors = ["Hannes Braun <hannesbraun@mail.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.0.19"
rosc = "0.5.2"
